databases:
  - name: coord-escolar-db
    plan: free

services:
  - type: web
    name: coord-escolar
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT app:app
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: coord-escolar-db
          property: connectionString
      - key: AUTO_SEED
        value: "1"
